Revert default assignments in Overlay2 props to avoid test flake in CI
This test passes locally but fails in CI. Need to investigate why this occurs.

```
Chrome Headless 124.0.6367.201 (Linux x86_64) <Popover> focus management when shouldReturnFocusOnClose={true} moves focus to overlay when opened FAILED
        Error: Uncaught focus should be inside overlay: expected null to not equal null
        ...
```