Call sinon.restore() after spying on console.error()
```
 OverlayToaster
    createAsync
       with default props
          reusing props object does not produce React errors
             1) TypeError: Attempted to wrap error which is already wrapped
                at checkWrappedMethod (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:162370:21)
                at wrapMethod (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:162435:13)
                at Function.spy (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:161469:16)
                at spy (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:161035:37)
                at Context.<anonymous> (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:145603:47)
                --------------
                Error: Stack Trace for original
                at extendObjectWithWrappedMethods (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:162476:34)
                at wrapMethod (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:162464:5)
                at Function.spy (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:161469:16)
                at spy (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:161035:37)
                at Context.<anonymous> (/var/folders/nh/jm76_9hj4nl0p2p82ylrzc2n086m2c/T/_karma_webpack_856918/commons.js:145603:47)
```