Switch to React.ReactNode for HotkeysProps children declaration
Fixing type error:
```
../table/src/cell/editableCell.tsx:198:17 - error TS2322: Type 'Element' is not assignable to type '(ReactElement<HotkeyProps, string | JSXElementConstructor<any>>[] & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined'.
  Type 'ReactElement<any, any>' is not assignable to type 'ReactElement<HotkeyProps, string | JSXElementConstructor<any>>[] & ReactPortal'.
    Type 'ReactElement<any, any>' is missing the following properties from type 'ReactElement<HotkeyProps, string | JSXElementConstructor<any>>[]': length, pop, push, concat, and 29 more.

198                 <Hotkey
                    ~~~~~~~
199                     key="edit-cell"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
203                     onKeyDown={this.handleEdit}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
204                 />
    ~~~~~~~~~~~~~~~~~~

  ../core/lib/esm/components/hotkeys/hotkeys.d.ts:17:5
    17     children?: Array<React.ReactElement<HotkeyProps>>;
           ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Hotkeys> & Pick<Readonly<HotkeysProps> & Readonly<...>, "className" | "children"> & InexactPartial<...> & InexactPartial<...>'

../table/src/table.tsx:504:25 - error TS2322: Type '(Element | Element[] | undefined)[]' is not assignable to type '(ReactElement<HotkeyProps, string | JSXElementConstructor<any>>[] & (boolean | ReactChild | ReactFragment | ReactPortal | null)) | undefined'.
  Type '(Element | Element[] | undefined)[]' is not assignable to type 'ReactElement<HotkeyProps, string | JSXElementConstructor<any>>[]'.
    Type 'Element | Element[] | undefined' is not assignable to type 'ReactElement<HotkeyProps, string | JSXElementConstructor<any>>'.
      Type 'undefined' is not assignable to type 'ReactElement<HotkeyProps, string | JSXElementConstructor<any>>'.

504         return <Hotkeys>{hotkeys.filter(element => element !== undefined)}</Hotkeys>;
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../core/lib/esm/components/hotkeys/hotkeys.d.ts:17:5
    17     children?: Array<React.ReactElement<HotkeyProps>>;
           ~~~~~~~~
    The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Hotkeys> & Pick<Readonly<HotkeysProps> & Readonly<...>, "className" | "children"> & InexactPartial<...> & InexactPartial<...>'
```